# Generated by Django 6.0.1 on 2026-01-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
