# Generated by Django 6.0.1 on 2026-01-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_at_time',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
